[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30", features = ["android-native-activity"] }
env_logger = "0.10"
log = "0.4"
anyhow = "1.0.98"
egui_winit_platform = "0.26.0"
egui = "0.31.1"
